# Generated by Django 5.0.9 on 2024-12-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
